/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.InterfaceBD;
import control.PersistenciaJPA;
import javax.swing.JOptionPane;

/**
 *
 * @author toazz
 */
public class PrincipalJF extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalJF
     */
    public PrincipalJF() {
        initComponents();
        
        carregarDashboard();
    }

    private void carregarDashboard(){
          try {
        InterfaceBD persistencia = new PersistenciaJPA();

        int finalizados = persistencia.getTotalJogosFinalizados();
        int emAndamento = persistencia.getTotalJogosEmAndamento();
        Double media = persistencia.getMediaNotas();

        lblFinalizados.setText("Jogos Finalizados: " + finalizados);
        lblEmAndamento.setText("Jogos em Andamento: " + emAndamento);
        lblMediaNotas.setText(String.format("Média de Notas: %.1f", media));

        persistencia.fecharConexao();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar estatísticas: " + e.getMessage());
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBemVindo = new javax.swing.JLabel();
        lblFinalizados = new javax.swing.JLabel();
        lblEmAndamento = new javax.swing.JLabel();
        lblMediaNotas = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        itemNovoJogo = new javax.swing.JMenuItem();
        menuGerenciar = new javax.swing.JMenu();
        itemBiblioteca = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        itemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBemVindo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblBemVindo.setText("Bem vindo(a) a sua Biblioteca de Jogos Pessoais");
        lblBemVindo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblFinalizados.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblFinalizados.setText("Jogos Finalizados: ");

        lblEmAndamento.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblEmAndamento.setText("Jogos em Andamento: ");

        lblMediaNotas.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblMediaNotas.setText("Média de Notas:");

        menuCadastro.setText("Cadastro");

        itemNovoJogo.setText("Novo Jogo");
        menuCadastro.add(itemNovoJogo);

        jMenuBar1.add(menuCadastro);

        menuGerenciar.setText("Gerenciar");

        itemBiblioteca.setText("Biblioteca");
        itemBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBibliotecaActionPerformed(evt);
            }
        });
        menuGerenciar.add(itemBiblioteca);

        jMenuBar1.add(menuGerenciar);

        menuAjuda.setText("Ajuda");

        itemSobre.setText("Sobre");
        menuAjuda.add(itemSobre);

        jMenuBar1.add(menuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFinalizados)
                    .addComponent(lblEmAndamento)
                    .addComponent(lblMediaNotas)
                    .addComponent(lblBemVindo))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblBemVindo)
                .addGap(30, 30, 30)
                .addComponent(lblFinalizados)
                .addGap(18, 18, 18)
                .addComponent(lblEmAndamento)
                .addGap(18, 18, 18)
                .addComponent(lblMediaNotas)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBibliotecaActionPerformed
        // TODO add your handling code here:
        GerenciamentoJogosJD telaGer = new GerenciamentoJogosJD(this, true); // 'this' é a TelaPrincipal
        telaGer.setVisible(true);
    }//GEN-LAST:event_itemBibliotecaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemBiblioteca;
    private javax.swing.JMenuItem itemNovoJogo;
    private javax.swing.JMenuItem itemSobre;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblEmAndamento;
    private javax.swing.JLabel lblFinalizados;
    private javax.swing.JLabel lblMediaNotas;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuGerenciar;
    // End of variables declaration//GEN-END:variables
}
